### PR TITLE
Multipart File Uploads via Retrofit

### PR DESCRIPTION
**Pull request by desperateCoder**
This also includes a bump of the Retrofit version (see https://github.com/nextcloud/Android-SingleSignOn/commit/ad266b943bbfc154c5e3d6cc4f95c0a3caf4d2ac) and a performance boost (see https://github.com/nextcloud/Android-SingleSignOn/commit/a9d899a936e5c137a8dcdb5ffac9110cfcf8d6d1)

### CODE REVIEW

**Comment by desperateCoder** [comment]
regarding the conflict: i'd suggest to accept mine :3

**Comment by desperateCoder** [comment]
Tags: https://github.com/nextcloud/Android-SingleSignOn/issues/151 , https://github.com/nextcloud/Android-SingleSignOn/issues/150

**Comment by David-Development** [comment]
Just looked through it. It looks great! 👍 Maybe we can come up with some more examples? What do you guys think of having an `/example` folder in the root dir where we put some code examples in. Otherwise the readme will be overloaded with too many informations as it already is.. 

Also it might make sense to visualize the flow of data when making a request using the sso library as for most people this is not clear yet and it makes debugging for us easier since even I do forget sometimes how the whole thing is implemented 😅

**Comment by tobiasKaminsky** [comment]
> Retrofit version (see [ad266b9](https://github.com/nextcloud/Android-SingleSignOn/commit/ad266b943bbfc154c5e3d6cc4f95c0a3caf4d2ac)) and a performance boost (see [a9d899a](https://github.com/nextcloud/Android-SingleSignOn/commit/a9d899a936e5c137a8dcdb5ffac9110cfcf8d6d1))

Next time it is better to have this separated, as it is then easier to review and test :-

**Comment by desperateCoder** [comment]
Sorry, didn't expect to get anything working anyway 😅

**Comment by desperateCoder** [comment]
Can i do anything to get this one merged? I'd resolve the conflict but i have no permissions in this repo...

**Comment by tobiasKaminsky** [comment]
You are on your own branch, so should be able to change it :-)

**Comment by tobiasKaminsky** [comment]
Let us get this in, and then add some examples in a later step :+1:

**Comment by desperateCoder** [comment]
Git says: `error: unknown option signoff`

**Comment by tobiasKaminsky** [comment]
It is -s, --signoff, eg. git commit -s

**Comment by desperateCoder** [comment]
Lol, my debian machine is running git 2.11.0. that command works from 2.13 up. kind of stuck here right now...

**Comment by tobiasKaminsky** [comment]
Then ignore it :-)
It is not that important.

**Comment by desperateCoder** [comment]
thanks! :sweat_smile: So is this ready to be merged and released? Do you need anything else?

**Pull request merged**
