### PR TITLE
Add Query-Requirement for Android 11 and later

### PR DESCRIPTION
**Pull request by newhinton**
Further information on the issue and source:
https://stackoverflow.com/questions/62345805/namenotfoundexception-when-calling-getpackageinfo-on-android-11

### CODE REVIEW

**Comment by stefan-niedermann** [comment]
Thank you for your contribution! :rocket: It makes perfectly sense to add this to the documentation until #282 has been merged.

May i ask which 3rd party you represent? It would be cool if you could post a link to your repository :slightly_smiling_face: 
We also have a Telegram group for this Single-Sign-On library. If you are interested, let me know at info@niedermann.it

**Review by stefan-niedermann — APPROVED** [review]

**Comment by newhinton** [comment]
At the moment i am just messing aroung, but my goal is to get a cookbook app to properly work. I am not sure if i just copy the notes app and rebuild where necessary or if i bring one of the existing app up to speed. When i make a decision, ill keep you updated ;)

**Comment by stefan-niedermann** [comment]
Sounds great :slightly_smiling_face: - but since there are already two open source cookbook apps available, you might want to consider joining forces instead of reinventing the wheel?
- https://play.google.com/store/apps/details?id=com.nextcloud_cookbook_flutter
- https://play.google.com/store/apps/details?id=de.micmun.android.nextcloudcookbook

Please note, that the Notes app recently got a huge refactoring (using `Room` instead of `SQLiteOpenHelper`), so you should make sure to fork from the very latest master.

**Comment by newhinton** [comment]
Generally you are right, but i have to make a decision what i want to rewrite. The existing apps have proper backends and ui, while the notes-app has a backend that supports the sso library, but has no fitting ui :D 


...and on top of that, i think the notes-app has an awesome ui/ux, so that would be an added bonus aswell

**Comment by stefan-niedermann** [comment]
Oh stop it, you!! 😳 You *might* want to have a [look at the Deck app](https://help.nextcloud.com/t/deck-android-1-18-cover-images/114194), but be aware, that the UI has some troubles there and is quite complex as well.

Anyway - welcome on board, looking forward to other contributions!

**Pull request merged**
