### PR TITLE
Migrate to Java 8 / AndroidX / update dependencies

### PR DESCRIPTION
**Pull request by David-Development**
@Unpublished is it okay if we merge your changes back into the main repository? We can also add you as a contributor if you like so you can work on this repo directly as well. 

One question that came up while looking through your changes. The commit called "remove synthetic accessors".. what is the purposes of it? Isn't it better (more appropriate) to have getter methods for them? 

Glad that someone uses it and takes a look at the code! :)

### CODE REVIEW

**Comment by Unpublished** [comment]
@David-Development 
> @Unpublished is it okay if we merge your changes back into the main repository?

Yes some of them are ready for this while others aren't yet. I'll split them.

> We can also add you as a contributor if you like so you can work on this repo directly as well.

I'd appreciate being added as a contributor.

> One question that came up while looking through your changes. The commit called "remove synthetic accessors".. what is the purposes of it? Isn't it better (more appropriate) to have getter methods for them?

There's more background to this [here](https://academy.realm.io/posts/360andev-jake-wharton-java-hidden-costs-android/) (starting at "Anonymous class (13:06)").
Making affected fields package-private is recommended solution for libraries as well.

Basicly it reduces the method count in the generated dex file. Adding methods would be contrary.
I just measured the impact on this library:
(536 -> 518)
It's small but it can add up since the library is likely to be included in multiple installed apps.

> Glad that someone uses it and takes a look at the code! :)

👍

**Comment by David-Development** [comment]
@Unpublished

> Yes some of them are ready for this while others aren't yet. I'll split them.

Okay, Awesome! :)

> I'd appreciate being added as a contributor.

@tobiasKaminsky @AndyScherzinger can you add @Unpublished as a contributor, please? I don't have the permission to do it.

> There's more background to this here (starting at "Anonymous class (13:06)").
> Making affected fields package-private is recommended solution for libraries as well.
> Basically it reduces the method count in the generated dex file. Adding methods would be contrary.
> I just measured the impact on this library: (536 -> 518)
> It's small but it can add up since the library is likely to be included in multiple installed apps.

Okay, I'll look into this again. After I briefly read an article about synthetic accessors, they talked only about nested classes (which we don't have). I'll take a look at the podcast later it might as well convince me that it's a good idea..
As of now I'm not sure if this an advantage that is worth having (the measured difference is "only" 18). Concerns: External applications can access these variables directly and Codacy complains about code smell.

**Comment by Unpublished** [comment]
> ...only about nested classes (which we don't have)

Yes there are accesses in nested classes, like `Builder` inside `NextcloudRequest` or the anonymous class of `ServiceConnection` inside `NextcloudAPI`.

I understand your concerns and I'm fine with keeping this only in my fork. Though external applications need to access them using the same package. So yes it is easier than using reflection but is still possible to recognize one shouldn't access them directly.

**Comment by tobiasKaminsky** [comment]
> > I'd appreciate being added as a contributor.
> 
> @tobiasKaminsky @AndyScherzinger can you add @Unpublished as a contributor, please? I don't have the permission to do it.

I added you. As a team member of android you should now have access to push branches to this and other android related repos.

**Comment by Unpublished** [comment]
> I added you. As a team member of android you should now have access to push branches to this and other android related repos.

@tobiasKaminsky Thank you for adding me to the android team :)

@David-Development This PR should now be fine to merge.

**Comment by David-Development** [comment]
@Unpublished Awesome, thank you! And thanks for reverting the changes with the modifiers. After watching the video by Jake, I'm still a little torn between whether it's a good or bad thing to get rid of the modifiers..

**Comment by Unpublished** [comment]
@David-Development I think it's okay to just leave these 18 extra methods there :)

Would you merge such a commit on [news-android](https://github.com/nextcloud/news-android) (~ 100 methods there)?

**Comment by David-Development** [comment]
> Would you merge such a commit on news-android (~ 100 methods there)?

@Unpublished I'm not quite sure if I understand that question correctly. Do you have some changes that you want to push?

**Comment by Unpublished** [comment]
@David-Development Sorry, I wasn't clear enough.
I am talking about a [remove synthetic accessors](https://github.com/Unpublished/news-android/commit/7b5e6c9b945cec6de5e2fe8a70c9ca4ec217a9b3) commit for news-android.
Just wanted to know if you feel different about changing the modifiers in an application vs (this) library.

**Pull request merged**
