### PR TITLE
Support rxjava3 return type

### PR DESCRIPTION
**Pull request by p1gp1g**
This add support for rxjava3 (to do this: https://github.com/UP-NextPush/android/commit/773862c7fe71cab7404406e08c74403d7bfe1c6f)

### CODE REVIEW

**Comment by David-Development** [comment]
@p1gp1g Thank you for adding support for rxjava3 - looks good to me! @stefan-niedermann @tobiasKaminsky any objections? 

Reminder to myself.. probably a good idea to migrate the news app to rxjava3 as well.. 😅

**Review by David-Development — APPROVED** [review]
min-sdk level for rxjava3 is 21+ (same as Single Sign On Library right now). So all good ✅

**Comment by p1gp1g** [comment]
I've just seen that it misses a change I haven't pushed

**Comment by p1gp1g** [comment]
Here it is

**Pull request merged**
