### PR TITLE
fix(void): Introduce new EmptyResponse type as successor for Void (#541)

### PR DESCRIPTION
**Pull request by stefan-niedermann**
:warning: **BREAKING CHANGE** :warning: 

- Fix for #541
- Can be tested [as described here](https://github.com/nextcloud/Android-SingleSignOn/issues/541#issuecomment-1893453525)

### CODE REVIEW

**Comment by David-Development** [comment]
Looks like a promising solution to the Void issue with AGP-8! I'm not really sure how to test it in the Okhttp3Helper .. does anyone actually use the Okhttp3Helper?

**Comment by stefan-niedermann** [comment]
@AndyScherzinger @tobiasKaminsky @David-Development can you please review the idea and check whether everything still works as expected?

This issue does prohibit 3rd party apps using recent build tools and I'd like to get it solved. Other opinions or ideas are welcome of course.

**Comment by David-Development** [comment]
@stefan-niedermann I created a few unit tests to cover the EmptyResponse check. I think the Nextcloud Files app would have to send the `EmptyResponse` as well to make it work properly (currently the unit test mocks the files api and returns a `EmptyResponse`). I think returning `Void` as an Observable is an edge case anyways where I don't even see any use-cases for. I'd say we can just merge this change (with a major version update) and keep an eye out if any of the third party apps break (and of course mention it as a breaking change).

My tests can be found here: https://github.com/nextcloud/Android-SingleSignOn/pull/589

**Comment by stefan-niedermann** [comment]
> I think the Nextcloud Files app would have to send the EmptyResponse as well 

This implies that the Files app does today send `Void` instances? How does this work? Just sending `null`?

> I think returning Void as an Observable is an edge case anyways where I don't even see any use-cases for. 

Well, the Deck Android App uses `Observable<Void>` as return type quite a lot (though @desperateCoder  is [working on replacing `Observable`s by `Call`s](https://github.com/stefan-niedermann/nextcloud-deck/tree/observable2call)).

> I'd say we can just merge this change (with a major version update) and keep an eye out if any of the third party apps break (and of course mention it as a breaking change).

Hm, What exactly would we need to adjust in the Files app to make this scenario work properly?

**Comment by David-Development** [comment]
@stefan-niedermann 
> This implies that the Files app does today send Void instances? How does this work? Just sending null?

I'm not 100% sure anymore since it's been a while but I looked at the code again and the files app doesn't know anything about types. So I think it we don't need any changes there..  ([ref](https://github.com/nextcloud/android/blob/master/app/src/main/java/com/nextcloud/android/sso/InputStreamBinder.java)). But I'm not sure anymore what exactly it will send back to our app in case we don't have a response.

If you are already using the `Observable<Void>` in the Deck app maybe you can test it there? And see what kind of response you are getting from the Files app? Or if the code already works as is.

**Review by David-Development — APPROVED** [review]

**Review by tobiasKaminsky — APPROVED** [review]

**Pull request merged**
