### PR TITLE
Use material 3 for error dialogs and sample app

### PR DESCRIPTION
**Pull request by AlvaroBrey**
Related: #494

| Before | After |
| --- | --- |
| Screenshot_1667823171 | Screenshot_1667823131 |

### CODE REVIEW

**Comment by David-Development** [comment]
Looks great to me! So much better than the old design 😅 @tobiasKaminsky @stefan-niedermann  Is this something we should publish in a new version right away?

**Comment by stefan-niedermann** [comment]
>  Is this something we should publish in a new version right away?

Actually I'd like to get a fix for #456 and #470 in first before releasing a new version cause I have quite a few users which regularly complain about those two issues :see_no_evil:

**Review by stefan-niedermann — APPROVED** [review]
Thanks for the awesome work @AlvaroBrey !

**Comment by David-Development** [comment]
@stefan-niedermann Good point about #470. Not sure when I'll have time to work on it.. I'm drowning in work right now and it doesn't look like it's getting any better in the next 2 weeks at least - I'll create a reminder though. If you already start investigating it let me know

**Pull request merged**
