### PR TITLE
VersionCheckHelper::getNextcloudFilesVersionCode only needs Context

### PR DESCRIPTION
**Pull request by stefan-niedermann**

### CODE REVIEW

**Comment by David-Development** [comment]
Does anyone has an idea why the build is failing.. Tried restarting it on Drone but it's still failing saying it's missing a symbol.. 🤔

**Comment by stefan-niedermann** [comment]
Oh, i think the `import` of `Context` might be missing....

**Comment by stefan-niedermann** [comment]
Build is fixed. What is this `DCO`-thingy?

**Comment by David-Development** [comment]
@stefan-niedermann awesome, thank you! The DCO means, that your commits are not signed 🙈

**Pull request merged**
