### PR TITLE
Add support to exclude existing accounts

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix https://github.com/nextcloud/Android-SingleSignOn/issues/106

TODO
- [ ] check other usages of pickNewAccount

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by David-Development** [comment]
I didn't have time yet to test the proposed changed. One question that came to my mind: Does this PR work when both apps have different signatures? I thought that `findAccounts` won't return the existing accounts if the user hasn't explicitly granted access to the accounts previously..?

**Comment by stefan-niedermann** [comment]
> I thought that findAccounts won't return the existing accounts if the user hasn't explicitly granted access to the accounts previously..?

This seems to be correct. I just tried it in a branch of the Notes app (given i have multiple accounts, and one of them already using in Notes), where `findAccounts()` will always return only the one account i already have approved.

Well, if `alloweableAccounts` match the result of `findAccounts`, the result will be, that the SSO lib assumes, there is no other account for import available and always opens the Weblogin-flow to add a completely new account.

**Comment by tobiasKaminsky** [comment]
findAccounts() should find all Accounts, and then all existingAccounts should be removed from it.
Hm. Maybe this is again about wrong testing as I tested it with the same Android Studio and not with different signatures.

If findAccounts cannot find all Accounts by Files app (and if we do not find a way), this is useless.

**Comment by tobiasKaminsky** [comment]
So, as far as I understand this does not work if we have different certificates, or?
Then let us postpone this until we have our own account manager in files app.

@David-Development ?

**Pull request closed without merging**
