### PR TITLE
add support for dev app

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
SSO has hard dependendcies to Nextcloud File app:
https://github.com/nextcloud/Android-SingleSignOn/blob/2ffb23412081ecf6b1bb81cce92a457f476cac43/src/main/java/com/nextcloud/android/sso/helper/VersionCheckHelper.java#L35-L40

https://github.com/nextcloud/Android-SingleSignOn/blob/53355e83c226679e01acf7192076baf221a806c4/src/main/java/com/nextcloud/android/sso/api/AidlNetworkRequest.java#L79-L84

https://github.com/nextcloud/Android-SingleSignOn/blob/c9dc53da8ffd8d7cd264dac8db113507410fd929/src/main/java/com/nextcloud/android/sso/AccountImporter.java#L278-L289

Question is how / if we can also support dev version there.

**Comment by David-Development** [comment]
For reference from our Telegram chat:

> Es gibt wirklich noch einiges zu beachten da der Service entsprechend der jeweiligen App gebunden werden muss. Bin mir noch nicht über Seiteneffekte bei Verwendung von multi Accounts im klaren. Erste Idee ist, dass wir uns für jeden Account speichern müssen von welchem package er ist und dementsprechend den Service binden müssen. Tobi hatte ja bereits die entsprechenden Stellen im Code angegeben. 

> Der Vollständigkeit wegen: hier der Bug-Report der schon seit einigen Monaten offen ist: https://github.com/nextcloud/Android-SingleSignOn/issues/46

@tobiasKaminsky Just thought about #49 .. this will make it quite hard to support both apps (normal and dev) as we need to connect to both apps and get an account list.

**Comment by tobiasKaminsky** [comment]
> need to connect to both apps and get an account list.

as this is a "one time" action, only when adding an account, I think this is ok.

**Comment by tobiasKaminsky** [comment]
This should be ready to test

**Comment by tobiasKaminsky** [comment]
@stefan-niedermann @desperateCoder can you both include this in your app and test?

**Comment by David-Development** [comment]
> as this is a "one time" action, only when adding an account, I think this is ok.

@tobiasKaminsky so for all the requests we'll just use the nextcloud files app? (and not the dev app?)

Does the normal app has access to the account data of the dev app? The actual account data is required for the actual network call to the nextcloud, isn't it?

**Comment by tobiasKaminsky** [comment]
> > as this is a "one time" action, only when adding an account, I think this is ok.
> 
> @tobiasKaminsky so for all the requests we'll just use the nextcloud files app? (and not the dev app?)
> 
> Does the normal app has access to the account data of the dev app? The actual account data is required for the actual network call to the nextcloud, isn't it?

No, I was referring to "fetch accounts from both apps". This is a "one time" action while adding accounts, which does not happen that offen.

As far as I tested, this PR allows to use both apps.
Please test it again so that it is really working as desired. I tested like this:
- official app: account on server A
- dev app: account on server B
- 3rd party app sees both accounts
- 3rd party app can switch between both accounts on the fly and do stuff 
(I tested it with deck)

**Comment by David-Development** [comment]
@tobiasKaminsky I was a little confused at first how the network requests will be made but I just saw that you added some logic to whether to connect to the nextcloud service or the nextcloud dev service. This line made things much clearer to me: https://github.com/nextcloud/Android-SingleSignOn/blob/c67f4a252dcf60feb9e4b607fcf28d12ac3b4333/src/main/java/com/nextcloud/android/sso/api/AidlNetworkRequest.java#L79

After running some tests, I couldn't select an account from the dev app as the line `final Account[] accounts = accMgr.getAccountsByType("nextcloud");` in the `AccountImporter` was only returning accounts of the type "nextcloud". After changing it to `final Account[] accounts = accMgr.getAccounts();` the login worked. How did you manage to get in running without that line?




This PR looks good to me! Great work! :) I created a PR with a few minor fixes in #65.

**Comment by tobiasKaminsky** [comment]
> How did you manage to get in running without that line?

Good question, :/
Maybe I tested it wrongly, but your fixes make sense.
Thanks for testing!

**Comment by desperateCoder** [comment]
Yay, thank you! When are you gonna build a release approximately?

**Comment by David-Development** [comment]
@desperateCoder right now! https://github.com/nextcloud/Android-SingleSignOn/releases/tag/0.4.0

**Comment by desperateCoder** [comment]
Thanks buddy! Hope you will be @ the NC conference, so I can offer you a beer for your support! Same for @tobiasKaminsky btw!

**Comment by desperateCoder** [comment]
@David-Development @tobiasKaminsky , just tested it for Deck, works great! Thanks again!

**Pull request merged**
