### PR TITLE
Add annotations

### PR DESCRIPTION
**Pull request by David-Development**
This PR adds support for using Retrofit annotations. Therefore developers don't have to create the `NextcloudRequest` objects themself.

### CODE REVIEW

**Comment by David-Development** [comment]
@desperateCoder Did you encounter any issues lately? Otherwise I'll merge this into master soon :)

**Comment by David-Development** [comment]
@z3ntu @PhieF Did anyone of you already test the annotations feature? If yes, did you encounter any issues so far?

Just updated the docs (https://github.com/nextcloud/Android-SingleSignOn/blob/96f48b4406e7b3a9de7e75cb4a383d19aeea9d12/README.md#how-to-use-this-library) -> Section 4.1.2

**Comment by desperateCoder** [comment]
Hey @David-Development ,
Nope, this baby is safe! Works really great, thanks!

**Comment by z3ntu** [comment]
The latest commit doesn't build on jitpack with the error

>    \> Minimum supported Gradle version is 4.10.1. Current version is 4.6. If using the gradle wrapper, try editing the distributionUrl in /home/jitpack/build/gradle/wrapper/gradle-wrapper.properties to gradle-4.10.1-all.zip

**Comment by AndyScherzinger** [comment]
@z3ntu thanks for the hint, fixed the gradle version, jitpack builds again
@David-Development I updated gradle to 4.10.1 incl. the hash, see https://github.com/nextcloud/Android-SingleSignOn/pull/40/commits/fece49d5b30ef5e519353160d5a8b454bc1e3c47

**Pull request merged**
