### PR TITLE
Fix for deck

### PR DESCRIPTION
**Pull request by stefan-niedermann**
cc @tobiasKaminsky @David-Development 

Please review and check especially whether or not the `clearAllAuthTokens` within the `pickNewAccount` is needed.

Thx!

### CODE REVIEW

**Comment by David-Development** [comment]
@stefan-niedermann Maybe you can elaborate a little why you removed the `clearAllAuthTokens` call? Did you run into some issues?

**Comment by stefan-niedermann** [comment]
Yes, basically everytime i add a new Account on the deck app, it will `clearAllAuthTokens` - Imagine this workflow:

1. Open Deck 1st time
2. Select initial user A
3. Add second user B
4. Switch between users

So as soon as i will do Step 3, user A will be deleted from the shared preferences, therefore i can no longer switch between the accounts with `NextcloudFilesAppAccountNotFoundException`.

Maybe @tobiasKaminsky is able to explain it better ^^

**Comment by David-Development** [comment]
@stefan-niedermann Got you.. I see. This is indeed a problem.

I'm trying to remember why we added it in the first place. Maybe #12 is related to this? Maybe @tobiasKaminsky knows more? 

Is there a case in which it is problematic to keep the tokens?

**Comment by tobiasKaminsky** [comment]
> I'm trying to remember why we added it in the first place. Maybe #12 is related to this? Maybe @tobiasKaminsky knows more?

I also thought about it… 
I think #12 is really the root cause of this.
We then should have this handled differently…
Two ideas:
- upon uninstallation the 3rd party app needs to unregister via SSO lib -> will be not reliable
- upon re-installation we know on files app that we have a non-matching account and we can present a dialog to re-authenticate (my preferred solution)

**Comment by David-Development** [comment]
When reinstalling an app the client app doesn't know anything about previous accounts, right? So I guess we can safely assume that in order to use the single sign on feature, it has to run the request authentication flow again which generates a new token. So we should be fine here. 

For reference: Permission Handling in the files app:
https://github.com/nextcloud/android/blob/086492b6d4f3514a84631d7c2539c0480438185c/src/main/java/com/owncloud/android/ui/activity/SsoGrantPermissionActivity.java#L55

The token is validated here:
https://github.com/nextcloud/android/blob/086492b6d4f3514a84631d7c2539c0480438185c/src/main/java/com/nextcloud/android/sso/InputStreamBinder.java#L220

Just wondering.. It looks like were doing it on a per package basis, correct? Doesn't that mean that once the user grants permission to one account, he'll have access to all accounts? Assumed that he knows the name of the other accounts.

**Comment by tobiasKaminsky** [comment]
I think we can merge this.

On a new PR I'll add/test this
- remove 3rd party app after everything worked & re-install it --> should ask again for authentication
- remove files app after everything worked & re-install it -> 3rd party also should again ask for authentication

On another one
- fix SSO to use triple of [account, package id, token] to authenticate.

**Comment by David-Development** [comment]
@stefan-niedermann @desperateCoder @tobiasKaminsky 
Just added two methods for handling TokenMismatchExceptions. Please note that we cannot simply recover from an TokenMismatch all the time as in Android 9 we need to explicitly grant permission to an account before we can request the token. 

https://github.com/nextcloud/Android-SingleSignOn/blob/master/src/main/java/com/nextcloud/android/sso/AccountImporter.java#L226

And in case you already use the SingleAccountHelper:
https://github.com/nextcloud/Android-SingleSignOn/blob/master/src/main/java/com/nextcloud/android/sso/helper/SingleAccountHelper.java#L60


Example usage: https://github.com/nextcloud/news-android/blob/master/News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderListActivity.java#L438

**Comment by tobiasKaminsky** [comment]
Niceeeeeeee

**Pull request merged**
